[versions]
agp = "8.2.2"
kotlin = "1.9.22"
coreKtx = "1.12.0"
appcompat = "1.6.1"
playServicesAds = "23.0.0"
playBilling = "6.2.1"
firebaseAnalytics = "21.6.1"
mavenPublish = "0.28.0"
composeBom = "2024.02.00"
appsflyer = "6.13.0"
facebook = "17.0.0"
installReferrer = "2.2"
constraintlayout = "2.1.4"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
play-billing = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "playBilling" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
appsflyer = { group = "com.appsflyer", name = "af-android-sdk", version.ref = "appsflyer" }
facebook-core = { group = "com.facebook.android", name = "facebook-core", version.ref = "facebook" }
install-referrer = { group = "com.android.installreferrer", name = "installreferrer", version.ref = "installReferrer" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish-helper = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
